#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

: "${SORIDORMI_COMMAND_X:=0.05}"
: "${SORIDORMI_COMMAND_Y:=0.0}"
: "${SORIDORMI_COMMAND_YAW:=0.0}"
: "${SORIDORMI_PHASE_FREQUENCY:=1.0}"
: "${SORIDORMI_ACTION_SCALE:=0.25}"
: "${SORIDORMI_MAX_MOTOR_VELOCITY:=5.24}"
: "${SORIDORMI_RUNTIME_LOG:=1}"
: "${SORIDORMI_RUNTIME_LOG_FORMAT:=mcap}"

export SORIDORMI_RUNTIME_MODE=onnx_policy
export SORIDORMI_COMMAND_X
export SORIDORMI_COMMAND_Y
export SORIDORMI_COMMAND_YAW
export SORIDORMI_PHASE_FREQUENCY
export SORIDORMI_ACTION_SCALE
export SORIDORMI_MAX_MOTOR_VELOCITY
export SORIDORMI_RUNTIME_LOG
export SORIDORMI_RUNTIME_LOG_FORMAT

./scripts/run_runtime_loop.sh
